[package]
name = "bevy_invaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_embedded_assets = "0.6.2"
rand = "0.8.5"

[workspace]
resolver = "2"
